### PR TITLE
read version from file

### PR DESCRIPTION
**Pull request by a16bitsysop**
Read version from docker-let’s-encrypt repo and tag with that and latest if it exists.

### CODE REVIEW

**Comment by patrickpissurno** [comment]
Hi, thanks for the PR.

I've looked into your commit, and I found it tagging the build with the current version (nice), but I could'nt find it tagging it with 'latest'.

Is it done automatically? I'm sorry if this is a rather naive question, but I'm not very experienced with Docker.

**Comment by a16bitsysop** [comment]
Yes you can omit latest and the only tag will be latest on docker hub, you have to add a version or other tag yourself.

The $TAG tags for version if present, if VERSION file is not there then TAG is empty/null so doesn't do anything.  The --tag after is yours minus the :latest as it will be tagged latest by docker hub.

**Comment by patrickpissurno** [comment]
I see you replaced test.docker.com with get.docker.com.

Does `docker buildx` still work after that change? It was supposed to be a preview feature, I’m not sure if it was already merged to stable.

**Comment by a16bitsysop** [comment]
Yes it builds a hello world type image with same platforms as yours and all the image ID numbers are different, if it’s tagging the same image with different tags the ID tags are the same.

Looking at the build logs it does install buildx with the script.

**Comment by patrickpissurno** [comment]
LGTM

**Pull request merged**
